// src/config/worlds.config.js
export const WORLDS = [
  {
    id: 0,
    name: 'Fact Family Farm',
    emoji: '🌾',
    accent: '#FFD700',
    description: 'Find missing parts within 20 — meet the friendly farm family!',
    conceptFocus: 'fact_family_find',
    boss: { name: 'Barnyard Bull', emoji: '🐂', reward: 'Farm Master Badge 🌾' },
  },
  {
    id: 1,
    name: 'Number Bond Meadow',
    emoji: '🌻',
    accent: '#FF6F61',
    description: 'Master part-part-whole number bonds within 30',
    conceptFocus: 'part_part_whole',
    boss: { name: 'Meadow Monster', emoji: '🌻', reward: 'Meadow Star Badge ⭐' },
  },
  {
    id: 2,
    name: 'Inverse Island',
    emoji: '🏝️',
    accent: '#4CAF50',
    description: 'Check inverse addition and subtraction pairs',
    conceptFocus: 'inverse_check',
    boss: { name: 'Captain Invert', emoji: '🏴‍☠️', reward: 'Inverse Master Badge ⚓' },
  },
  {
    id: 3,
    name: 'Bar Model Bay',
    emoji: '⛵',
    accent: '#AB47BC',
    description: 'Use Singapore bar models to find missing parts',
    conceptFocus: 'bar_model',
    boss: { name: 'Baron Bar', emoji: '🏗️', reward: 'Bar Builder Badge ⛵' },
  },
  {
    id: 4,
    name: 'Take-Away Temple',
    emoji: '🏛️',
    accent: '#29B6F6',
    description: 'Solve subtraction by turning it into addition',
    conceptFocus: 'subtraction_as_addition',
    boss: { name: 'Temple Guardian', emoji: '🗿', reward: 'Temple Champion Badge 🏛️' },
  },
  {
    id: 5,
    name: 'Missing Addend Mart',
    emoji: '🛒',
    accent: '#EC407A',
    description: 'Solve missing addend equations (□ + a = b)',
    conceptFocus: 'missing_addend',
    boss: { name: 'Mystery Merchant', emoji: '🛍️', reward: 'Equation Solver Badge 🛒' },
  },
  {
    id: 6,
    name: 'Comparison Canyon',
    emoji: '🏜️',
    accent: '#FF9800',
    description: 'Solve "how many more" comparison word problems',
    conceptFocus: 'how_many_more',
    boss: { name: 'Canyon Colossus', emoji: '⛰️', reward: 'Comparison Pro Badge 🏜️' },
  },
  {
    id: 7,
    name: 'Fact Family Factory',
    emoji: '🏭',
    accent: '#26A69A',
    description: 'Build all 4 number sentences from 3 numbers',
    conceptFocus: 'complete_family',
    boss: { name: 'Factory Foreman', emoji: '🤖', reward: 'Factory Master Badge 🏭' },
  },
  {
    id: 8,
    name: 'Story Problem Peaks',
    emoji: '🏔️',
    accent: '#5C6BC0',
    description: 'Solve real-world fair and market subtraction stories',
    conceptFocus: 'word_problems',
    boss: { name: 'Peak Phoenix', emoji: '🦅', reward: 'Story Hero Badge 🏔️' },
  },
  {
    id: 9,
    name: 'Inverse Grand Kingdom',
    emoji: '👑',
    accent: '#FFC107',
    description: 'Ultimate mastery of addition & subtraction relations (up to 100)!',
    conceptFocus: 'mixed_mastery',
    boss: { name: 'Math King Arthur', emoji: '👑', reward: 'Grand Master Crown 👑' },
  },
];

export const BADGES = [
  { id: 'first_step',        name: 'First Discovery',     icon: '🌱', description: 'Solved your first math problem' },
  { id: 'hot_streak',        name: 'Hot Streak',          icon: '🔥', description: '5 correct answers in a row' },
  { id: 'fact_detective',    name: 'Fact Detective',      icon: '🔍', description: 'Completed all Simulate stations' },
  { id: 'inverse_master',    name: 'Inverse Master',      icon: '⚡', description: '80%+ accuracy in any world' },
  { id: 'perfect_triangle',  name: 'Perfect Triangle',    icon: '💎', description: 'Scored 10/10 in a world' },
  { id: 'boss_slayer',       name: 'Boss Slayer',         icon: '👑', description: 'Defeated a World Boss' },
  { id: 'grand_master',      name: 'Grand Master',        icon: '🌟', description: 'Completed the entire journey' },
];

export const XP_REWARDS = {
  CORRECT: 10,
  STREAK_BONUS: 15,
  STATION_COMPLETE: 25,
  WORLD_COMPLETE: 50,
  BOSS_WIN: 100,
};
