export const audioMap = {
  "Welcome to Subtraction within 100! Let's discover the secret connection between addition and subtraction.": "/assets/audio/intro_welcome.mp3",
  "If 48 plus 35 equals 83... can you find two hidden subtraction secrets inside?": "/assets/audio/wonder_01.mp3",
  "Addition and subtraction undo each other. They are called inverse operations, like a lock and its key!": "/assets/audio/wonder_02.mp3",
  "Knowing one addition fact gives you two subtraction facts instantly! Let's discover how.": "/assets/audio/wonder_03.mp3",
  "Lily and Max baked 63 sandwiches one morning.": "/assets/audio/story_panel1.mp3",
  "By noon, only 27 sandwiches were left on the shelf.": "/assets/audio/story_panel2.mp3",
  "Max scratched his head. How many sandwiches did we sell? I can't figure it out!": "/assets/audio/story_panel3.mp3",
  "Lily had an idea! She drew a fact family triangle with 63 at the top, 27 on one side, and a question mark on the other.": "/assets/audio/story_panel4.mp3",
  "63 minus 27 equals 36. They sold 36 sandwiches! One addition fact revealed the answer instantly!": "/assets/audio/story_panel5.mp3",
  "They wrote all four facts on the chalkboard: 27 plus 36 equals 63, 36 plus 27 equals 63, 63 minus 27 equals 36, and 63 minus 36 equals 27!": "/assets/audio/story_panel6.mp3",
  "Station A! Let's use base-ten blocks to take away and see subtraction in action.": "/assets/audio/sim_a_intro.mp3",
  "Station B! Use the fact family triangle to find the missing number.": "/assets/audio/sim_b_intro.mp3",
  "Station C! Can you write the subtraction sentence that matches the addition sentence?": "/assets/audio/sim_c_intro.mp3",
  "Brilliant! You've got it!": "/assets/audio/feedback_correct_01.mp3",
  "Excellent work! The inverse relationship helped you!": "/assets/audio/feedback_correct_02.mp3",
  "Outstanding! You're a subtraction superstar!": "/assets/audio/feedback_correct_03.mp3",
  "Good try! Remember to use the fact family triangle.": "/assets/audio/feedback_wrong_01.mp3",
  "Not quite! Think about the inverse relationship.": "/assets/audio/feedback_wrong_02.mp3",
  "Badge unlocked! Curious Coder! You completed the Wonder and Story phases!": "/assets/audio/badge_curious_coder.mp3",
  "Badge unlocked! Sim Scientist! You completed all three simulation stations!": "/assets/audio/badge_sim_scientist.mp3",
  "Badge unlocked! Sub Solver! You scored over 80 correct answers!": "/assets/audio/badge_sub_solver.mp3",
  "Badge unlocked! Inverse Master! You scored perfect ten out of ten in a world!": "/assets/audio/badge_inv_master.mp3",
  "Badge unlocked! Streak Champion! You answered 12 questions in a row correctly!": "/assets/audio/badge_streak_champ.mp3",
  "Badge unlocked! Journey Hero! You completed all five phases. What an achievement!": "/assets/audio/badge_journey_hero.mp3",
  "Wonderful! You completed this world! Keep going to unlock the next challenge!": "/assets/audio/world_complete.mp3",
  "Amazing! You've completed all ten worlds! You are a true Subtraction Master!": "/assets/audio/all_worlds_done.mp3",
  "Let's take a moment to think about everything you've learned today.": "/assets/audio/reflect_intro.mp3",
  "Congratulations! You've completed the Subtraction within 100 module. What a fantastic journey!": "/assets/audio/results_final.mp3"
};
